require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**'
    - 'bin/**'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Style/Documentation:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Metrics/BlockLength:
  Enabled: false