version: '3.1'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: /bin/bash
    tty: true
    volumes:
      - .:/twitter-api
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data